[project]
name = "norma"
version = "0.1"
description = "Backpropagating through building codes"
readme = "README.md"
requires-python = ">=3.10"
authors = [{name = "Rafael Pastrana"}]
license = "Apache-2.0"
classifiers = []
dependencies = [

]

[dependency-groups]
dev = [
    "pytest"
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


[project.urls]
Homepage = "https://github.com/arpastrana/norma"
Changelog = "https://github.com/arpastrana/norma/releases"
Issues = "https://github.com/arpastrana/norma/issues"
CI = "https://github.com/arpastrana/norma/actions"

